### ISSUE TITLE
Fortran 90 code

### ISSUE THREAD

**Issue by rs028** [Mistra-UEA/Mistra#10]
Conversion of the entire codebase to Fortran 90 (as mentioned in issue #6). This is partially done, but not completely. @JosueBock what is the current status?

**Comment by JosueBock** [comment]
2 files converted to Fortran 90:
- str.f90
- common_modules.f90
See the latest merged pull request: https://github.com/Mistra-UEA/Mistra/commit/04aefcd303a08a0f87d68361d157c20316fe46cd

**Comment by JosueBock** [comment]
one more file converted: outp.f90
See commit https://github.com/Mistra-UEA/Mistra/commit/ff9496c4983367554e877b8539fe815b173c7379

**Comment by JosueBock** [comment]
kpp.f converted into kpp.f90

This was the last file which may regularly be updated (change in chemical species, ...) and for which the F90 free format is more convenient to use.

Since the remaining F77 files (aer/gas/tot.f, budget files, jrate and out_netCDF) are not expected to be regularly updated, I consider this "issue" (which was actually not an issue since it is completely valid to combine F77 and F90 files) now closed.
