### ISSUE TITLE
Compilation fail

### ISSUE THREAD

**Issue by rs028** [Mistra-UEA/Mistra#6]
I am using the version of KPP provided with Mistra.
 I tried to compile the model but it fails:

```
cd src/mech
make

KPP is parsing the equation file
Fatal error : atoms : can't read file
```

It seems `atoms` is required by `src/mech/master.spc` but there is no file with that name in the directory. Is there a file missing?

@pb866 did you manage to compile without errors?

**Comment by pb866** [comment]
Same for me, when I tried to run the model over Christmas. I don't think that's due to kpp though. As far as I understood @JosueBock, this kpp version contains just a few bug fixes, e.g., the acknowledgement of the correct line length of fixed form fortran. I assume, it is missing a file with some definitions for when we define species in Mistra, but I didn't have the time to look into it, yet.

**Comment by pb866** [comment]
I had another quick look over the weekend, there is a file atoms in `kpp/models` with the atoms definitions. I think, thats the file kpp wants, but I don't know, why it is not found. I am not too familiar with kpp. A work around might be (not tested, just speculation) to delete the `#include atoms` statement in `master.spc` and use `= IGNORE;` for every species as we don't do mass balance checks anyways. Another option I can think of is to use the original kpp and scripts I have written to reformat files to acknowledged the fixed format f77 line length. Have you tested with the original kpp @rs028?

**Comment by rs028** [comment]
I haven't tried. I will. 
BTW, I am coming to York tomorrow, maybe we can find some time to talk about this?

**Comment by rs028** [comment]
It does not work with KPP 2.2.3 (the last official version on http://people.cs.vt.edu/asandu/Software/Kpp/).

If I copy the `atoms` file from `kpp/models/` into `src/mech/` it complains that there are "too many species" (???).

If I do as you suggest (i.e., delete `#include atoms` and set everything to `IGNORE` in `master.spc` I get an error message:

    Fatal error : rosenbrock.def: Can't read file

`rosenbrock.def` is a file in `$KPP_HOME/int`. My guess is that this is a matter of how KPP is installed and/or configured rather than its version (although the version issue also need clarification, see #7).

@JosueBock do you have any clues on what is going on?

**Comment by JosueBock** [comment]
> @JosueBock do you have any clues on what is going on?

I guess that something went wrong during your KPP installation, since I had no problem to install it from scratch.
The "atoms" file is not the reason, as Peter found, it is provided in the KPP distribution (in subdirectory models).

When using KPP, if it does not find this file, it means that the link is not correct, so I guess the problem might arise from your environment variables definitions: in your .bashrc (or maybe .cshrc) file, you have to set the KPP_HOME environment variable. Please ensure that it points to the correct directory.

**Comment by rs028** [comment]
I will have another go and let you know. This also reminds me that the model seems to be using both bash and csh scripts, correct me if I am wrong.
Since the syntax is slightly different it would probably be good to pick one and convert the other scripts to it. I will open another issues about it.

**Comment by JosueBock** [comment]
All scripts in mech subdirectory are csh scripts.
The only bash script that I noticed is the param file.
But for both scripts, regular users should not have to deal with these files (well, for the param file, only define path), so I don't think this is crucial.
Feel free to open an issue about this, but this will clearly be a low priority in my opinion (lower priority than converting all Fortran code in Fortran90, for instance).

**Comment by JosueBock** [comment]
Please reopen this issue in case of troubles when compiling.
All recent tests on various platforms are successful regarding the compilation.
