### ISSUE TITLE
Convert bash scripts

### ISSUE THREAD

**Issue by rs028** [Mistra-UEA/Mistra#9]
Need to make sure that all scripts are `csh` scripts, for consistency.
At the moment the following scripts are `bash` scripts:
- src/plots/newfold.sh
- param/param_jjb1
- src/plots/make_ps.sc

**Comment by JosueBock** [comment]
Hello,
For several reasons, I don't see a real need to convert `bash` scripts into `csh` scripts:
- both are valid, and similarly there are currently `.f` and `.f90` code files. For sure, having as little language variations could be better, but in the end, the result will be identical, and there are lots of developments which would be more useful to spend time on.
- both are available on most machines (including team servers and supercomputers ), or can be installed.
- if a conversion had to be made, I would rather convert `csh` scripts into `bash` scripts, the latter being the most known I think
- `csh` scripts (in the `mech` directory) do not need to be edited, since they are tightly linked to the KPP output. So apart from expert modellers who would make major changes in the whole code structure, no one should have to dig into these scripts. So regular users sould only have to know one language, used in the param script.

I thus close this issue, but don't hesitate to re-open it if needed.
